// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbcmoxibgmgmhnikwgrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiY21veGliZ21nbWhuaWt3Z3JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjY0ODksImV4cCI6MjA2MjA0MjQ4OX0.skC-c9783mv-BnUIVykXv7JXKW0WIutdTXir4VGqaBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);